# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh
# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.

ZSH_THEME="hdforce"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"
# Comment this out to disable weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"
# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"
# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"
# Uncomment following line if you want red dots to be displayed while waiting for completion
COMPLETION_WAITING_DOTS="true"
# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git brew gradle zsh-syntax-highlighting zsh-autosuggestions virtualenv conda-env conda-zsh-completion zsh-autopair)
source $ZSH/oh-my-zsh.sh


# EXPORTS 
export EDITOR="vim"
export GOPATH=$HOME/go
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/opt/local/sbin:/Users/satej/.local/bin:/usr/local/go/bin

# ALIASES
alias hgrep="history | grep"
alias :q="exit"
alias :r="source ~/.zshrc"

# git aliases
function clonecd() {  git clone $1 && cd $(basename ${1/.git//}) ; }
function mergefrom() { orig=$(git rev-parse --abbrev-ref HEAD) ; git checkout $1 && git pull && git checkout $orig && git merge $1 ; }
alias status="git status"
alias add="git add"
alias push="git push"
alias pusho="git push origin"
alias commit="git commit -m"
alias checkout="git checkout"
alias co="git checkout"
alias tag="git tag"
alias clone="clonecd"
alias fetch="git fetch"
alias pull="git pull"
alias pullo="git pull origin"
alias merge="git merge"
alias branch="git branch"

# automatically ls after cd
function list_all() {
    emulate -L zsh
    ls 
}
chpwd_functions=(omz_termsupport_chpwd list_all)

# MAC OS X SPECIFIC SETTINGS
# show hide all files
function hidedotfiles(){
    defaults write com.apple.finder AppleShowAllFiles -bool NO
    killall Finder
}
function showdotfiles(){
    defaults write com.apple.finder AppleShowAllFiles -bool YES
    killall Finder
}

function growl(){
  echo $'\e]9;'$1'\007' 
}

function weather() {
  curl wttr.in/$1
}

function moon() {
  curl wttr.in/Moon
}

# syntax highlighting
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern)
ZSH_HIGHLIGHT_STYLES[default]=none
ZSH_HIGHLIGHT_STYLES[unknown-token]=fg=009
ZSH_HIGHLIGHT_STYLES[reserved-word]=fg=075
ZSH_HIGHLIGHT_STYLES[alias]=fg=106
ZSH_HIGHLIGHT_STYLES[builtin]=fg=106
ZSH_HIGHLIGHT_STYLES[function]=fg=106
ZSH_HIGHLIGHT_STYLES[command]=fg=106
ZSH_HIGHLIGHT_STYLES[precommand]=fg=white
ZSH_HIGHLIGHT_STYLES[commandseparator]=none
ZSH_HIGHLIGHT_STYLES[hashed-command]=fg=009
ZSH_HIGHLIGHT_STYLES[path]=bg=235
ZSH_HIGHLIGHT_STYLES[path_approx]=bg=234
ZSH_HIGHLIGHT_STYLES[path_prefix]=bg=234
ZSH_HIGHLIGHT_STYLES[globbing]=fg=075
ZSH_HIGHLIGHT_STYLES[history-expansion]=fg=white
ZSH_HIGHLIGHT_STYLES[single-hyphen-option]=none
ZSH_HIGHLIGHT_STYLES[double-hyphen-option]=none
ZSH_HIGHLIGHT_STYLES[back-quoted-argument]=none
ZSH_HIGHLIGHT_STYLES[single-quoted-argument]=fg=214
ZSH_HIGHLIGHT_STYLES[double-quoted-argument]=fg=214
ZSH_HIGHLIGHT_STYLES[dollar-double-quoted-argument]=fg=214
ZSH_HIGHLIGHT_STYLES[back-double-quoted-argument]=fg=214
ZSH_HIGHLIGHT_STYLES[assign]=none
ZSH_HIGHLIGHT_STYLES[bracket-level-1]='fg=075,bold'
ZSH_HIGHLIGHT_STYLES[bracket-level-2]='fg=074,bold'
ZSH_HIGHLIGHT_STYLES[bracket-level-3]='fg=039,bold'
ZSH_HIGHLIGHT_STYLES[bracket-level-4]='fg=038,bold'
source ~/.oh-my-zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh


export CONDA_AUTO_ACTIVATE_BASE=false

# >>> mamba initialize >>>
# !! Contents within this block are managed by 'mamba shell init' !!
export MAMBA_EXE='/home/t-satejsoman/miniforge3/bin/mamba';
export MAMBA_ROOT_PREFIX='/home/t-satejsoman/.local/share/mamba';
__mamba_setup="$("$MAMBA_EXE" shell hook --shell zsh --root-prefix "$MAMBA_ROOT_PREFIX" 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__mamba_setup"
else
    alias mamba="$MAMBA_EXE"  # Fallback on help from mamba activate
fi
unset __mamba_setup
# <<< mamba initialize <<<

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/t-satejsoman/miniforge3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/t-satejsoman/miniforge3/etc/profile.d/conda.sh" ]; then
        . "/home/t-satejsoman/miniforge3/etc/profile.d/conda.sh"
    else
        export PATH="/home/t-satejsoman/miniforge3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<
conda deactivate

. "$HOME/.local/bin/env"
